# Generated by Django 4.1 on 2022-11-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=300, null=True)),
                ('house_number', models.CharField(blank=True, max_length=300, null=True)),
                ('postcode', models.IntegerField(blank=True, null=True)),
                ('telephone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('besttime', models.CharField(blank=True, max_length=300, null=True)),
                ('services', models.CharField(blank=True, max_length=300, null=True)),
                ('contact_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('phone', models.CharField(blank=True, max_length=300, null=True)),
                ('postcode', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('subscription_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
